### ISSUE TITLE
Test example does not compile

### ISSUE THREAD

**Issue by martincarles** [eddow/vue-golden-layout#25] opened 2018-12-10 09:56 UTC
Hi @eddow, thanks for your work on this library. Much appreciated.
We're trying to use it in our projects but we keep getting the "Dynamic golden-layout components should be named templates instead" message.
Could you please provide some working examples of templates and names slots working together?
The test example you provide doesn't compile.

Thanks in advance!

**Comment by eddow** [comment] 2018-12-10 12:53
Hello,

Then the issue is that the test example does not compile :) Could you please provide the compilation errors so we could solve it ?

**Comment by eddow** [comment] 2018-12-10 13:53
Damn... I can't reproduce ... O.o
I'm searching blindly what it could be but I am still lost....

**Comment by eddow** [comment] 2018-12-10 14:20
So,
The bug comes indeed from a library used here (an [issue](https://github.com/vuejs/vue-class-component/issues/296) has been opened)

Beside, I changed the status of a function (from global to exported), it should do the job.

Could you please pull the last version and confirm nothing else breaks the test application ?

**Comment by eddow** [comment] 2018-12-10 15:51
@martincarles I will close it for now - please feel free to re-open if something is still wrong.

**Closed by eddow** 2018-12-10 15:51 UTC
Labels: bug
